version: "3"
services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: parvah
      POSTGRES_PASSWORD: backend
      POSTGRES_DB: parvah
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/_data
  parvah-backend:
    build: ./
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://parvah:backend@postgres/parvah
    ports:
      - 8443:8443
    depends_on:
      - postgres